# Generated by Django 6.0 on 2026-01-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Dua for anxiety', max_length=200)),
                ('arabic_text', models.TextField(help_text='The actual Arabic script')),
                ('transliteration', models.TextField(blank=True, help_text='English pronunciation')),
                ('translation_en', models.TextField(help_text='English meaning')),
                ('translation_ur', models.TextField(blank=True, help_text='Urdu meaning')),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='MuslimDuaApp.category')),
            ],
        ),
    ]
